// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxQxoo55dWrFefyspqkBjm-9-2bLphLDw',
    appId: '1:452860760300:web:cee28d0583f5e5089155c9',
    messagingSenderId: '452860760300',
    projectId: 'project2-783d1',
    authDomain: 'project2-783d1.firebaseapp.com',
    storageBucket: 'project2-783d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSC5rs4hnIew3QmvGuTSQDeb9iDzTykV8',
    appId: '1:452860760300:android:c68ba6fae2de9dc69155c9',
    messagingSenderId: '452860760300',
    projectId: 'project2-783d1',
    storageBucket: 'project2-783d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1PezGyGPDyYNFoUK7J16EZydFS86AaCI',
    appId: '1:452860760300:ios:b3113b5b17e2226a9155c9',
    messagingSenderId: '452860760300',
    projectId: 'project2-783d1',
    storageBucket: 'project2-783d1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1PezGyGPDyYNFoUK7J16EZydFS86AaCI',
    appId: '1:452860760300:ios:7b400bea92789dd69155c9',
    messagingSenderId: '452860760300',
    projectId: 'project2-783d1',
    storageBucket: 'project2-783d1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
